# First, open up python interpreter in terminal
# Next, execute file from python interpreter
exec(open("ormDatabase.py").read())

# Populate the user table
# First value is user id, second is name, third is class
AddUser(CreateUser(1111, "Wayne Gretsky", 4))
AddUser(CreateUser(2222, "Sidney Crosby", 3))
AddUser(CreateUser(3333, "Brock Boeser", 1))
AddUser(CreateUser(4444, "Daniel Sedin", 3))
AddUser(CreateUser(5555, "Ryan Getslaf", 2))

# List users by ID:
PrintList(ListUsers())
# List users by Name:
PrintList(ListUsersByName())

# Populate the book table
# First value is isbn, second is title, third is author,
# fourth is the user the book is connected to.
# Use the FindUser function to return the user matching the ID.
# Listing ID is generated by table, so no entry is required.
AddBook(CreateBook("1610020243", "Textbook of Neonatal Resuscitation", "Gary M Weiner", 80, FindUser(1111)))
AddBook(CreateBook("1118324579", "Materials Science and Engineering: An Introduction", "William D. Callister Jr.", 90, FindUser(3333)))
AddBook(CreateBook("0321616677", "Evolutionary Analysis", "Jon. C Herron", 110, FindUser(4444)))
AddBook(CreateBook("0321907981", "Technical Communication Today", "Richard Johnson-Sheehan", 70, FindUser(2222)))
AddBook(CreateBook("1285852702", "Delmar's Standard Textbook of Electricity", "Stephen Herman", 60, FindUser(5555)))
AddBook(CreateBook("0323319742", "Mosby's Textbook for Nursing Assistants", "Sheila A. Sorrentino", 140, FindUser(1111)))
AddBook(CreateBook("0138147574", "Signals and Systems", "Alan V. Oppenheim", 120,  FindUser(2222)))
AddBook(CreateBook("1848726953", "Textbook of Clinical Neuropsychology", "Joel E. Morgan", 100, FindUser(4444)))

# List books by book title
PrintList(ListBooks())
# List books by author
PrintList(ListBooksByAuthor())
# List books by isbn
PrintList(ListBooksByISBN())
# List books from a certain author
PrintList(ListBooksFromAuthor("Gary M Weiner"))
# List books from a certain user
# Once again use the FindUser function to find
# a user in the user table by their id
PrintList(ListBooksFromUser((FindUser(1111)))

# Fuzzy search for any titles containing the following search term
PrintList(SearchFor('neonatal'))